const infoList = {
  "one-nav": {
    "background": "./images/main/simpler/nav-1.png",
    "oneNavImg1": "./images/main/simpler/foto-1.png",
    "oneNavText1": "Портрет рисует художник.Детально прорисовывает все части портрета! ",
    "oneNavImg2": "/images/main/simpler/foto-2.png",
    "oneNavText2": "Покрытие Вашей картины защитным акриловым лаком или текстурным гелем. ",
    "oneNavImg3": "/images/main/simpler/foto-3.png",
    "oneNavText3": "Яркость и прочность материалов более 100 лет! Холст сохранит свое натяжение и не провиснет!",
    "oneNavImg4": "/images/main/simpler/foto-4.png",
    "oneNavText4": "Каждая картина упаковывается подарочную бумагу и украшается бантом!",
  },
  "two-nav": {
    "background": "./images/main/simpler/nav-2.png",
    "oneNavImg1": "./images/main/simpler/foto-4.png",
    "oneNavText1": "Покрытие Вашей картины защитным акриловым лаком или текстурным гелем.",
    "oneNavImg2": "/images/main/simpler/foto-3.png",
    "oneNavText2": "Яркость и прочность материалов более 100 лет! Холст сохранит свое натяжение и не провиснет!",
    "oneNavImg3": "/images/main/simpler/foto-2.png",
    "oneNavText3": "Каждая картина упаковывается подарочную бумагу и украшается бантом!",
    "oneNavImg4": "/images/main/simpler/foto-1.png",
    "oneNavText4": "Портрет рисует художник.Детально прорисовывает все части портрета!",
  },
  "three-nav": {
    "background": "./images/main/simpler/nav-3.png",
    "oneNavImg1": "./images/main/simpler/foto-3.png",
    "oneNavText1": "Яркость и прочность материалов более 100 лет! Холст сохранит свое натяжение и не провиснет!",
    "oneNavImg2": "./images/main/simpler/foto-2.png",
    "oneNavText2": "Каждая картина упаковывается подарочную бумагу и украшается бантом!",
    "oneNavImg3": "./images/main/simpler/foto-1.png",
    "oneNavText3": "Портрет рисует художник.Детально прорисовывает все части портрета!",
    "oneNavImg4": "./images/main/simpler/foto-4.png",
    "oneNavText4": "Покрытие Вашей картины защитным акриловым лаком или текстурным гелем.",  
  },
  "four-nav": {
    "background": "./images/main/simpler/nav-4.png",
    "oneNavImg1": "./images/main/simpler/foto-2.png",
    "oneNavText1": "Каждая картина упаковывается подарочную бумагу и украшается бантом!",
    "oneNavImg2": "./images/main/simpler/foto-1.png",
    "oneNavText2": "Портрет рисует художник.Детально прорисовывает все части портрета!",
    "oneNavImg3": "./images/main/simpler/foto-4.png",
    "oneNavText3": "Покрытие Вашей картины защитным акриловым лаком или текстурным гелем.",
    "oneNavImg4": "./images/main/simpler/foto-3.png",
    "oneNavText4": "Яркость и прочность материалов более 100 лет! Холст сохранит свое натяжение и не провиснет!",   
  },
  "five-nav": {
    "background": "./images/main/simpler/nav-5.png",
    "oneNavImg1": "./images/main/simpler/foto-3.png",
    "oneNavText1": "Яркость и прочность материалов более 100 лет! Холст сохранит свое натяжение и не провиснет!",
    "oneNavImg2": "./images/main/simpler/foto-4.png",
    "oneNavText2": "Каждая картина упаковывается подарочную бумагу и украшается бантом!",
    "oneNavImg3": "./images/main/simpler/foto-2.png",
    "oneNavText3": "Портрет рисует художник.Детально прорисовывает все части портрета!",
    "oneNavImg4": "./images/main/simpler/foto-1.png",
    "oneNavText4": "Покрытие Вашей картины защитным акриловым лаком или текстурным гелем.",  
  },
}

export default infoList;